apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: joaooliveira/dio-k8s-project-database:1.0
        args:
        - "ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: postgresql
        ports:
        - containerPort: 3306
          name: postgresql
        
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  templates:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: joaooliveira/dio-k8s-project-backend:1.0
        imagePullPolicy: Always
        ports: 
        - containerPort: 80