apiVersion: v1
kind: Service
metadata: 
  name: php
spec:
  selector:
    app: php
  ports:
    - port: 80
      targetPort: 80
  type: loadBalancer

---

apiVersion: v1
kind: Service
metadata: 
  name: postgresql-connection
spec:
  ports:
  - port: 5432
  selector: 
    app: postgresql
  clusterIp: None

